const cardData = [
  {
    id: 1,
    title: "Amazing Villa For Sale",
    categories: "Real Estate",
    price: "$5000",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/1-1-q0w9fymet6prygmdvus8tiwm9itajexsih14p3wmtc.jpg",
  },
  {
    id: 2,
    title: "Red Classic Car",
    categories: "Vehicles Classic Cars",
    price: "$80000",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/11-1-q0vvsc3a9nptkoqhmuhw732h5fz3mi7ul5fni2uf7k.jpg",
  },

  {
    id: 3,
    title: "Iphone 14 Pro Max",
    categories: "Apple Mobile Phones",
    price: "$950",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/6-3-q0w4ivszasb4r1u5wb8g37khiblyg5y7i0m3yign0g.jpg",
  },
  {
    id: 4,
    title: "Nike Fancy Shoes",
    categories: "Shoes Fashion",
    price: "$1500",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/nike-q0w59q32gh1wa6ul5wwxafqc6fba90i9uv99aynxc0.jpg",
  },
  {
    id: 5,
    title: "Best 4K Drone",
    categories: "Electronics",
    price: "3500",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/dron-q0w67fkpjl72mrvxbzga7fif2v65a9bqtph3v6oo74.jpg",
  },
  {
    id: 6,
    title: "Wood Table For Sale",
    categories: "Furniture",
    price: "$900",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/t3-1-q0w7hgq68i7l7b0tjdrjtbc2d6a98n2itjm4y0flhc.jpg",
  },
  {
    id: 7,
    title: "Computer Table For Sale",
    categories: "Furniture",
    price: "$6000",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/t1-1-q0w7heuhuu50k33jucyaobt56ejit8v25ab5zgidts.jpg",
  },
  {
    id: 8,
    title: "Fancy Lamps For Sale",
    categories: "Furniture",
    price: "5000",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/6-1-q0w908rkix75t7gbo26u4hp4nkabtmjdooatsj7mv4.jpg",
  },
  {
    id: 9,
    title: "Fancy Lamps For Sale",
    categories: "Furniture",
    price: "5000",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/6-1-q0w908rkix75t7gbo26u4hp4nkabtmjdooatsj7mv4.jpg",
  },
  {
    id: 10,
    title: "Double Bed Set",
    categories: "Beds   Furniture ",
    price: "$2200",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/bad-q0w7h89mizw0atd3ws3wovgx0pfybd4xsdqrmis51c.jpg",
  },
  {
    id: 11,
    title: "Villa For Sale",
    categories: "Real Estate   For rent  ",
    price: "$800",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/21-q0vvqqr4orjbwh1rxnpngzjcwxtpkyw819n1877fr4.jpg",
  },
  {
    id: 12,
    title: "House For Sale",
    categories: "Real Estate",
    price: " $85000",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/jho-q0w1yi7zmxunqo0rbdqe1irnt2xbz17vgsi81jfiio.jpg",
  },
  {
    id: 13,
    title: "Sofa Cam Bed",
    categories: "Sofas   Furniture",
    price: "6000",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/10-3-q0w909pepr8g4teyiklgozgl8y5p1bn40syb9t68ow.jpg",
  },
  {
    id: 14,
    title: "Fancy Sofa Set",
    categories: "Sofas   Furniture  ",
    price: "$600",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/sofa1-q0w7hcyth62fwv6a5c51jca7zmssdunlh1070wl668.jpg",
  },
  {
    id: 15,
    title: "Office Chair For Sale",
    categories: "Furniture",
    price: "$200",
    img: "https://classiads.designinvento.net/elementor/classiads-flow/wp-content/uploads/elementor/thumbs/c2-q0w7hb353hzv9n90gbbsecrasv21ygg4srp82cnyio.jpg",
  },
];

export default cardData;
